name: CI v2

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        module:
          - arc

    steps:
      - name: Run pipeline
        uses: dagger/dagger-for-github@eba69b4dddb54eddfdb51a88eb7fd86957137630 # v5.4.0
        with:
          verb: call
          module: github.com/${{ github.repository }}/${{ matrix.module }}/tests@${{ github.ref }}
          args: all
          # cloud-token: ${{ secrets.DAGGER_CLOUD_TOKEN }}
          version: "0.11.1"
